package com.cat.client

object Actions {
    const val CONNECT = "com.cat.client.action.CONNECT"
    const val DISCONNECT = "com.cat.client.action.DISCONNECT"
    const val RECONNECT = "com.cat.client.action.RECONNECT"
    const val REFRESH = "com.cat.client.action.REFRESH"
    const val SWITCH_CONNECTION = "com.cat.client.action.SWITCH_CONNECTION"
    const val TEST_CONNECTION_DELAYS = "com.cat.client.action.TEST_CONNECTION_DELAYS"
    const val TEST_CONNECTION_SPEED = "com.cat.client.action.TEST_CONNECTION_SPEED"
    const val CANCEL_CONNECTION_SPEED_TEST = "com.cat.client.action.CANCEL_CONNECTION_SPEED_TEST"
    const val PAUSE_CONNECTION_DELAY_TEST = "com.cat.client.action.PAUSE_CONNECTION_DELAY_TEST"
    const val RESUME_CONNECTION_DELAY_TEST = "com.cat.client.action.RESUME_CONNECTION_DELAY_TEST"
    const val CANCEL_CONNECTION_DELAY_TEST = "com.cat.client.action.CANCEL_CONNECTION_DELAY_TEST"
    const val STATE_CHANGED = "com.cat.client.action.STATE_CHANGED"
    const val CONNECTION_DELAY_TEST_CHANGED = "com.cat.client.action.CONNECTION_DELAY_TEST_CHANGED"
    const val CONNECTION_SPEED_TEST_CHANGED = "com.cat.client.action.CONNECTION_SPEED_TEST_CHANGED"

    const val EXTRA_STATE = "extra_state"
    const val EXTRA_ERROR = "extra_error"
    const val EXTRA_NOTICE = "extra_notice"
    const val EXTRA_SESSION_STARTED_AT_ELAPSED_MS = "extra_session_started_at_elapsed_ms"
    const val EXTRA_CONNECTION_COUNTRY_FLAG = "extra_connection_country_flag"
    const val EXTRA_DEBUG_FRONTING_IP = "extra_debug_fronting_ip"
    const val EXTRA_CONNECTION_DETAILS = "extra_connection_details"
    const val EXTRA_SUBSCRIPTION_ID = "extra_subscription_id"
    const val EXTRA_CONNECTION_FINGERPRINT = "extra_connection_fingerprint"
    const val EXTRA_ACTIVE_SUBSCRIPTION_ID = "extra_active_subscription_id"
    const val EXTRA_ACTIVE_CONNECTION_TAG = "extra_active_connection_tag"
    const val EXTRA_ACTIVE_CONNECTION_FINGERPRINT = "extra_active_connection_fingerprint"
    const val EXTRA_CHAIN_HOP_COUNT = "extra_chain_hop_count"
    const val EXTRA_LIVE_SELECTOR_READY = "extra_live_selector_ready"
    const val EXTRA_SELECTABLE_CONNECTION_FINGERPRINTS = "extra_selectable_connection_fingerprints"
    const val EXTRA_APP_INITIATED = "extra_app_initiated"
    const val EXTRA_ALWAYS_ON = "extra_always_on"
    const val EXTRA_LOCKDOWN = "extra_lockdown"
    const val EXTRA_CONNECTION_TYPES = "extra_connection_types"
    const val EXTRA_CONNECTION_FINGERPRINTS = "extra_connection_fingerprints"
    const val EXTRA_DELAY_TEST_ID = "extra_delay_test_id"
    const val EXTRA_DELAY_TEST_STATUS = "extra_delay_test_status"
    const val EXTRA_DELAY_TEST_COMPLETED = "extra_delay_test_completed"
    const val EXTRA_DELAY_TEST_TOTAL = "extra_delay_test_total"
    const val EXTRA_DELAY_TEST_AVAILABLE = "extra_delay_test_available"
    const val EXTRA_DELAY_TEST_FINISHED = "extra_delay_test_finished"
    const val EXTRA_DELAY_TEST_PAUSED = "extra_delay_test_paused"
    const val EXTRA_DELAY_TEST_ERROR = "extra_delay_test_error"
    const val EXTRA_SPEED_TEST_ID = "extra_speed_test_id"
    const val EXTRA_SPEED_TEST_STATUS = "extra_speed_test_status"
    const val EXTRA_SPEED_TEST_ERROR = "extra_speed_test_error"

    const val DELAY_TEST_PREPARING = "preparing"
    const val DELAY_TEST_STARTED = "started"
    const val DELAY_TEST_PROGRESS = "progress"
    const val DELAY_TEST_COMPLETED = "completed"
    const val DELAY_TEST_FAILED = "failed"
    const val DELAY_TEST_CANCELED = "canceled"

    const val SPEED_TEST_PREPARING = "preparing"
    const val SPEED_TEST_STARTED = "started"
    const val SPEED_TEST_COMPLETED = "completed"
    const val SPEED_TEST_FAILED = "failed"
    const val SPEED_TEST_CANCELED = "canceled"

    fun resolveServiceAction(action: String?, appInitiated: Boolean): String? {
        return if (appInitiated) action else CONNECT
    }
}
