package com.cat.client

/**
 * Human-friendly locations for the edge codes returned by /cdn-cgi/trace.
 *
 * An anycast IP does not have one permanent country. The edge code is the
 * location that actually answered the probe, so it is more useful than trying
 * to geolocate the shared IP address itself.
 */
data class EdgeLocation(
    val colo: String,
    val city: String,
    val country: String,
    val countryCode: String,
) {
    val flag: String get() = countryCode.toFlagEmoji()
    val label: String get() = "$city, $country"
}

object EdgeLocationCatalog {
    private val locations = mapOf(
        "ABQ" to EdgeLocation("ABQ", "Albuquerque", "United States", "US"),
        "ACC" to EdgeLocation("ACC", "Accra", "Ghana", "GH"),
        "ADL" to EdgeLocation("ADL", "Adelaide", "Australia", "AU"),
        "AGA" to EdgeLocation("AGA", "Agadir", "Morocco", "MA"),
        "AGR" to EdgeLocation("AGR", "Agra", "India", "IN"),
        "AKL" to EdgeLocation("AKL", "Auckland", "New Zealand", "NZ"),
        "ALA" to EdgeLocation("ALA", "Almaty", "Kazakhstan", "KZ"),
        "ALG" to EdgeLocation("ALG", "Algiers", "Algeria", "DZ"),
        "AMD" to EdgeLocation("AMD", "Ahmedabad", "India", "IN"),
        "AMM" to EdgeLocation("AMM", "Amman", "Jordan", "JO"),
        "AMS" to EdgeLocation("AMS", "Amsterdam", "Netherlands", "NL"),
        "ANC" to EdgeLocation("ANC", "Anchorage", "United States", "US"),
        "AOI" to EdgeLocation("AOI", "Ancona", "Italy", "IT"),
        "ARN" to EdgeLocation("ARN", "Stockholm", "Sweden", "SE"),
        "ASU" to EdgeLocation("ASU", "Asuncion", "Paraguay", "PY"),
        "ATH" to EdgeLocation("ATH", "Athens", "Greece", "GR"),
        "ATL" to EdgeLocation("ATL", "Atlanta", "United States", "US"),
        "AUH" to EdgeLocation("AUH", "Abu Dhabi", "United Arab Emirates", "AE"),
        "BAH" to EdgeLocation("BAH", "Manama", "Bahrain", "BH"),
        "BAL" to EdgeLocation("BAL", "Baltimore", "United States", "US"),
        "BAQ" to EdgeLocation("BAQ", "Barranquilla", "Colombia", "CO"),
        "BBI" to EdgeLocation("BBI", "Bhubaneswar", "India", "IN"),
        "BBU" to EdgeLocation("BBU", "Bucharest", "Romania", "RO"),
        "BCN" to EdgeLocation("BCN", "Barcelona", "Spain", "ES"),
        "BEG" to EdgeLocation("BEG", "Belgrade", "Serbia", "RS"),
        "BEL" to EdgeLocation("BEL", "Belem", "Brazil", "BR"),
        "BER" to EdgeLocation("BER", "Berlin", "Germany", "DE"),
        "BGF" to EdgeLocation("BGF", "Bangui", "Central African Republic", "CF"),
        "BGW" to EdgeLocation("BGW", "Baghdad", "Iraq", "IQ"),
        "BHD" to EdgeLocation("BHD", "Belfast", "United Kingdom", "GB"),
        "BHX" to EdgeLocation("BHX", "Birmingham", "United Kingdom", "GB"),
        "BIO" to EdgeLocation("BIO", "Bilbao", "Spain", "ES"),
        "BIQ" to EdgeLocation("BIQ", "Biarritz", "France", "FR"),
        "BJS" to EdgeLocation("BJS", "Beijing", "China", "CN"),
        "BKI" to EdgeLocation("BKI", "Kota Kinabalu", "Malaysia", "MY"),
        "BKK" to EdgeLocation("BKK", "Bangkok", "Thailand", "TH"),
        "BKO" to EdgeLocation("BKO", "Bamako", "Mali", "ML"),
        "BMG" to EdgeLocation("BMG", "Bloomington", "United States", "US"),
        "BNA" to EdgeLocation("BNA", "Nashville", "United States", "US"),
        "BNU" to EdgeLocation("BNU", "Blumenau", "Brazil", "BR"),
        "BOD" to EdgeLocation("BOD", "Bordeaux", "France", "FR"),
        "BOG" to EdgeLocation("BOG", "Bogota", "Colombia", "CO"),
        "BOI" to EdgeLocation("BOI", "Boise", "United States", "US"),
        "BOM" to EdgeLocation("BOM", "Mumbai", "India", "IN"),
        "BOS" to EdgeLocation("BOS", "Boston", "United States", "US"),
        "BRU" to EdgeLocation("BRU", "Brussels", "Belgium", "BE"),
        "BSB" to EdgeLocation("BSB", "Brasilia", "Brazil", "BR"),
        "BSR" to EdgeLocation("BSR", "Basra", "Iraq", "IQ"),
        "BTS" to EdgeLocation("BTS", "Bratislava", "Slovakia", "SK"),
        "BUD" to EdgeLocation("BUD", "Budapest", "Hungary", "HU"),
        "BUE" to EdgeLocation("BUE", "Buenos Aires", "Argentina", "AR"),
        "BUF" to EdgeLocation("BUF", "Buffalo", "United States", "US"),
        "BUH" to EdgeLocation("BUH", "Bucharest", "Romania", "RO"),
        "BUR" to EdgeLocation("BUR", "Burbank", "United States", "US"),
        "BWN" to EdgeLocation("BWN", "Bandar Seri Begawan", "Brunei", "BN"),
        "BZE" to EdgeLocation("BZE", "Belize City", "Belize", "BZ"),
        "CAI" to EdgeLocation("CAI", "Cairo", "Egypt", "EG"),
        "CAN" to EdgeLocation("CAN", "Guangzhou", "China", "CN"),
        "CBB" to EdgeLocation("CBB", "Cochabamba", "Bolivia", "BO"),
        "CBR" to EdgeLocation("CBR", "Canberra", "Australia", "AU"),
        "CCU" to EdgeLocation("CCU", "Kolkata", "India", "IN"),
        "CDG" to EdgeLocation("CDG", "Paris", "France", "FR"),
        "CDT" to EdgeLocation("CDT", "Tarragona", "Spain", "ES"),
        "CEB" to EdgeLocation("CEB", "Cebu", "Philippines", "PH"),
        "CGK" to EdgeLocation("CGK", "Jakarta", "Indonesia", "ID"),
        "CGO" to EdgeLocation("CGO", "Zhengzhou", "China", "CN"),
        "CGP" to EdgeLocation("CGP", "Chattogram", "Bangladesh", "BD"),
        "CGQ" to EdgeLocation("CGQ", "Changchun", "China", "CN"),
        "CGR" to EdgeLocation("CGR", "Campo Grande", "Brazil", "BR"),
        "CHC" to EdgeLocation("CHC", "Christchurch", "New Zealand", "NZ"),
        "CHS" to EdgeLocation("CHS", "Charleston", "United States", "US"),
        "CJB" to EdgeLocation("CJB", "Coimbatore", "India", "IN"),
        "CJU" to EdgeLocation("CJU", "Jeju", "South Korea", "KR"),
        "CKG" to EdgeLocation("CKG", "Chongqing", "China", "CN"),
        "CMB" to EdgeLocation("CMB", "Colombo", "Sri Lanka", "LK"),
        "CMH" to EdgeLocation("CMH", "Columbus", "United States", "US"),
        "CNF" to EdgeLocation("CNF", "Belo Horizonte", "Brazil", "BR"),
        "CNX" to EdgeLocation("CNX", "Chiang Mai", "Thailand", "TH"),
        "COD" to EdgeLocation("COD", "Cody", "United States", "US"),
        "COK" to EdgeLocation("COK", "Kochi", "India", "IN"),
        "COR" to EdgeLocation("COR", "Cordoba", "Argentina", "AR"),
        "CPH" to EdgeLocation("CPH", "Copenhagen", "Denmark", "DK"),
        "CPT" to EdgeLocation("CPT", "Cape Town", "South Africa", "ZA"),
        "CRL" to EdgeLocation("CRL", "Charleroi", "Belgium", "BE"),
        "CRP" to EdgeLocation("CRP", "Corpus Christi", "United States", "US"),
        "CSX" to EdgeLocation("CSX", "Changsha", "China", "CN"),
        "CTU" to EdgeLocation("CTU", "Chengdu", "China", "CN"),
        "CUR" to EdgeLocation("CUR", "Willemstad", "Curacao", "CW"),
        "CVG" to EdgeLocation("CVG", "Cincinnati", "United States", "US"),
        "CWB" to EdgeLocation("CWB", "Curitiba", "Brazil", "BR"),
        "CZX" to EdgeLocation("CZX", "Changzhou", "China", "CN"),
        "DAC" to EdgeLocation("DAC", "Dhaka", "Bangladesh", "BD"),
        "DAR" to EdgeLocation("DAR", "Dar es Salaam", "Tanzania", "TZ"),
        "DAY" to EdgeLocation("DAY", "Dayton", "United States", "US"),
        "DEL" to EdgeLocation("DEL", "Delhi", "India", "IN"),
        "DEN" to EdgeLocation("DEN", "Denver", "United States", "US"),
        "DFW" to EdgeLocation("DFW", "Dallas", "United States", "US"),
        "DMM" to EdgeLocation("DMM", "Dammam", "Saudi Arabia", "SA"),
        "DOH" to EdgeLocation("DOH", "Doha", "Qatar", "QA"),
        "DPS" to EdgeLocation("DPS", "Denpasar", "Indonesia", "ID"),
        "DTW" to EdgeLocation("DTW", "Detroit", "United States", "US"),
        "DUB" to EdgeLocation("DUB", "Dublin", "Ireland", "IE"),
        "DUR" to EdgeLocation("DUR", "Durban", "South Africa", "ZA"),
        "DUS" to EdgeLocation("DUS", "Dusseldorf", "Germany", "DE"),
        "DVO" to EdgeLocation("DVO", "Davao", "Philippines", "PH"),
        "DXB" to EdgeLocation("DXB", "Dubai", "United Arab Emirates", "AE"),
        "EBB" to EdgeLocation("EBB", "Kampala", "Uganda", "UG"),
        "EDI" to EdgeLocation("EDI", "Edinburgh", "United Kingdom", "GB"),
        "ENU" to EdgeLocation("ENU", "Enugu", "Nigeria", "NG"),
        "EPR" to EdgeLocation("EPR", "Esperance", "Australia", "AU"),
        "EZE" to EdgeLocation("EZE", "Buenos Aires", "Argentina", "AR"),
        "FAE" to EdgeLocation("FAE", "Faroe Islands", "Faroe Islands", "FO"),
        "FAO" to EdgeLocation("FAO", "Faro", "Portugal", "PT"),
        "FAT" to EdgeLocation("FAT", "Fresno", "United States", "US"),
        "FCO" to EdgeLocation("FCO", "Rome", "Italy", "IT"),
        "FIH" to EdgeLocation("FIH", "Kinshasa", "Congo, Democratic Republic", "CD"),
        "FLN" to EdgeLocation("FLN", "Florianopolis", "Brazil", "BR"),
        "FOC" to EdgeLocation("FOC", "Fuzhou", "China", "CN"),
        "FOR" to EdgeLocation("FOR", "Fortaleza", "Brazil", "BR"),
        "FRA" to EdgeLocation("FRA", "Frankfurt", "Germany", "DE"),
        "FUK" to EdgeLocation("FUK", "Fukuoka", "Japan", "JP"),
        "GBE" to EdgeLocation("GBE", "Gaborone", "Botswana", "BW"),
        "GDN" to EdgeLocation("GDN", "Gdansk", "Poland", "PL"),
        "GIG" to EdgeLocation("GIG", "Rio de Janeiro", "Brazil", "BR"),
        "GIZ" to EdgeLocation("GIZ", "Jazan", "Saudi Arabia", "SA"),
        "GND" to EdgeLocation("GND", "St. George's", "Grenada", "GD"),
        "GOT" to EdgeLocation("GOT", "Gothenburg", "Sweden", "SE"),
        "GRU" to EdgeLocation("GRU", "Sao Paulo", "Brazil", "BR"),
        "GUA" to EdgeLocation("GUA", "Guatemala City", "Guatemala", "GT"),
        "GUM" to EdgeLocation("GUM", "Hagatna", "Guam", "GU"),
        "GVA" to EdgeLocation("GVA", "Geneva", "Switzerland", "CH"),
        "GYN" to EdgeLocation("GYN", "Goiania", "Brazil", "BR"),
        "HAK" to EdgeLocation("HAK", "Haikou", "China", "CN"),
        "HAM" to EdgeLocation("HAM", "Hamburg", "Germany", "DE"),
        "HAN" to EdgeLocation("HAN", "Hanoi", "Vietnam", "VN"),
        "HAV" to EdgeLocation("HAV", "Havana", "Cuba", "CU"),
        "HEL" to EdgeLocation("HEL", "Helsinki", "Finland", "FI"),
        "HET" to EdgeLocation("HET", "Hohhot", "China", "CN"),
        "HFA" to EdgeLocation("HFA", "Haifa", "Israel", "IL"),
        "HKG" to EdgeLocation("HKG", "Hong Kong", "Hong Kong", "HK"),
        "HNL" to EdgeLocation("HNL", "Honolulu", "United States", "US"),
        "HRE" to EdgeLocation("HRE", "Harare", "Zimbabwe", "ZW"),
        "HYD" to EdgeLocation("HYD", "Hyderabad", "India", "IN"),
        "IAD" to EdgeLocation("IAD", "Washington", "United States", "US"),
        "IAH" to EdgeLocation("IAH", "Houston", "United States", "US"),
        "ICN" to EdgeLocation("ICN", "Seoul", "South Korea", "KR"),
        "IND" to EdgeLocation("IND", "Indianapolis", "United States", "US"),
        "ISB" to EdgeLocation("ISB", "Islamabad", "Pakistan", "PK"),
        "IST" to EdgeLocation("IST", "Istanbul", "Turkey", "TR"),
        "ISU" to EdgeLocation("ISU", "Sulaymaniyah", "Iraq", "IQ"),
        "JAX" to EdgeLocation("JAX", "Jacksonville", "United States", "US"),
        "JED" to EdgeLocation("JED", "Jeddah", "Saudi Arabia", "SA"),
        "JIB" to EdgeLocation("JIB", "Djibouti", "Djibouti", "DJ"),
        "JNB" to EdgeLocation("JNB", "Johannesburg", "South Africa", "ZA"),
        "JOG" to EdgeLocation("JOG", "Yogyakarta", "Indonesia", "ID"),
        "JTR" to EdgeLocation("JTR", "Santorini", "Greece", "GR"),
        "JUL" to EdgeLocation("JUL", "Juliaca", "Peru", "PE"),
        "KBP" to EdgeLocation("KBP", "Kyiv", "Ukraine", "UA"),
        "KEF" to EdgeLocation("KEF", "Reykjavik", "Iceland", "IS"),
        "KHH" to EdgeLocation("KHH", "Kaohsiung", "Taiwan", "TW"),
        "KHI" to EdgeLocation("KHI", "Karachi", "Pakistan", "PK"),
        "KIN" to EdgeLocation("KIN", "Kingston", "Jamaica", "JM"),
        "KIX" to EdgeLocation("KIX", "Osaka", "Japan", "JP"),
        "KLD" to EdgeLocation("KLD", "Tver", "Russia", "RU"),
        "KMG" to EdgeLocation("KMG", "Kunming", "China", "CN"),
        "KRK" to EdgeLocation("KRK", "Krakow", "Poland", "PL"),
        "KTM" to EdgeLocation("KTM", "Kathmandu", "Nepal", "NP"),
        "KUL" to EdgeLocation("KUL", "Kuala Lumpur", "Malaysia", "MY"),
        "KWE" to EdgeLocation("KWE", "Guiyang", "China", "CN"),
        "KWI" to EdgeLocation("KWI", "Kuwait City", "Kuwait", "KW"),
        "LAN" to EdgeLocation("LAN", "Lansing", "United States", "US"),
        "LAS" to EdgeLocation("LAS", "Las Vegas", "United States", "US"),
        "LAX" to EdgeLocation("LAX", "Los Angeles", "United States", "US"),
        "LCA" to EdgeLocation("LCA", "Larnaca", "Cyprus", "CY"),
        "LED" to EdgeLocation("LED", "St. Petersburg", "Russia", "RU"),
        "LEX" to EdgeLocation("LEX", "Lexington", "United States", "US"),
        "LFW" to EdgeLocation("LFW", "Lome", "Togo", "TG"),
        "LGA" to EdgeLocation("LGA", "New York", "United States", "US"),
        "LHE" to EdgeLocation("LHE", "Lahore", "Pakistan", "PK"),
        "LHR" to EdgeLocation("LHR", "London", "United Kingdom", "GB"),
        "LIM" to EdgeLocation("LIM", "Lima", "Peru", "PE"),
        "LIS" to EdgeLocation("LIS", "Lisbon", "Portugal", "PT"),
        "LJU" to EdgeLocation("LJU", "Ljubljana", "Slovenia", "SI"),
        "LOS" to EdgeLocation("LOS", "Lagos", "Nigeria", "NG"),
        "LPA" to EdgeLocation("LPA", "Las Palmas", "Spain", "ES"),
        "LPB" to EdgeLocation("LPB", "La Paz", "Bolivia", "BO"),
        "LPL" to EdgeLocation("LPL", "Liverpool", "United Kingdom", "GB"),
        "LSA" to EdgeLocation("LSA", "Los Angeles", "United States", "US"),
        "LUN" to EdgeLocation("LUN", "Lusaka", "Zambia", "ZM"),
        "LUX" to EdgeLocation("LUX", "Luxembourg", "Luxembourg", "LU"),
        "LXR" to EdgeLocation("LXR", "Luxor", "Egypt", "EG"),
        "MAA" to EdgeLocation("MAA", "Chennai", "India", "IN"),
        "MAD" to EdgeLocation("MAD", "Madrid", "Spain", "ES"),
        "MAN" to EdgeLocation("MAN", "Manchester", "United Kingdom", "GB"),
        "MAO" to EdgeLocation("MAO", "Manaus", "Brazil", "BR"),
        "MBA" to EdgeLocation("MBA", "Mombasa", "Kenya", "KE"),
        "MCI" to EdgeLocation("MCI", "Kansas City", "United States", "US"),
        "MCN" to EdgeLocation("MCN", "Macon", "United States", "US"),
        "MCT" to EdgeLocation("MCT", "Muscat", "Oman", "OM"),
        "MDC" to EdgeLocation("MDC", "Manado", "Indonesia", "ID"),
        "MDE" to EdgeLocation("MDE", "Medellin", "Colombia", "CO"),
        "MDL" to EdgeLocation("MDL", "Mandalay", "Myanmar", "MM"),
        "MED" to EdgeLocation("MED", "Madinah", "Saudi Arabia", "SA"),
        "MEL" to EdgeLocation("MEL", "Melbourne", "Australia", "AU"),
        "MEM" to EdgeLocation("MEM", "Memphis", "United States", "US"),
        "MEX" to EdgeLocation("MEX", "Mexico City", "Mexico", "MX"),
        "MFE" to EdgeLocation("MFE", "McAllen", "United States", "US"),
        "MFM" to EdgeLocation("MFM", "Macao", "Macao", "MO"),
        "MGL" to EdgeLocation("MGL", "Montgomery", "United States", "US"),
        "MHD" to EdgeLocation("MHD", "Mashhad", "Iran", "IR"),
        "MIA" to EdgeLocation("MIA", "Miami", "United States", "US"),
        "MLE" to EdgeLocation("MLE", "Male", "Maldives", "MV"),
        "MLU" to EdgeLocation("MLU", "Monroe", "United States", "US"),
        "MNL" to EdgeLocation("MNL", "Manila", "Philippines", "PH"),
        "MOW" to EdgeLocation("MOW", "Moscow", "Russia", "RU"),
        "MPM" to EdgeLocation("MPM", "Maputo", "Mozambique", "MZ"),
        "MRS" to EdgeLocation("MRS", "Marseille", "France", "FR"),
        "MRU" to EdgeLocation("MRU", "Port Louis", "Mauritius", "MU"),
        "MSN" to EdgeLocation("MSN", "Madison", "United States", "US"),
        "MSP" to EdgeLocation("MSP", "Minneapolis", "United States", "US"),
        "MSQ" to EdgeLocation("MSQ", "Minsk", "Belarus", "BY"),
        "MSS" to EdgeLocation("MSS", "Massena", "United States", "US"),
        "MUC" to EdgeLocation("MUC", "Munich", "Germany", "DE"),
        "MVD" to EdgeLocation("MVD", "Montevideo", "Uruguay", "UY"),
        "MXP" to EdgeLocation("MXP", "Milan", "Italy", "IT"),
        "NAG" to EdgeLocation("NAG", "Nagpur", "India", "IN"),
        "NAY" to EdgeLocation("NAY", "Beijing", "China", "CN"),
        "NBG" to EdgeLocation("NBG", "New Orleans", "United States", "US"),
        "NCL" to EdgeLocation("NCL", "Newcastle", "United Kingdom", "GB"),
        "NDJ" to EdgeLocation("NDJ", "N'Djamena", "Chad", "TD"),
        "NGB" to EdgeLocation("NGB", "Ningbo", "China", "CN"),
        "NGO" to EdgeLocation("NGO", "Nagoya", "Japan", "JP"),
        "NKG" to EdgeLocation("NKG", "Nanjing", "China", "CN"),
        "NRT" to EdgeLocation("NRT", "Tokyo", "Japan", "JP"),
        "NUA" to EdgeLocation("NUA", "Nuuk", "Greenland", "GL"),
        "NUE" to EdgeLocation("NUE", "Nuremberg", "Germany", "DE"),
        "OKA" to EdgeLocation("OKA", "Okinawa", "Japan", "JP"),
        "OKC" to EdgeLocation("OKC", "Oklahoma City", "United States", "US"),
        "OMA" to EdgeLocation("OMA", "Omaha", "United States", "US"),
        "ONT" to EdgeLocation("ONT", "Ontario", "United States", "US"),
        "OOL" to EdgeLocation("OOL", "Gold Coast", "Australia", "AU"),
        "OPO" to EdgeLocation("OPO", "Porto", "Portugal", "PT"),
        "ORD" to EdgeLocation("ORD", "Chicago", "United States", "US"),
        "ORF" to EdgeLocation("ORF", "Norfolk", "United States", "US"),
        "ORK" to EdgeLocation("ORK", "Cork", "Ireland", "IE"),
        "ORN" to EdgeLocation("ORN", "Oran", "Algeria", "DZ"),
        "OSL" to EdgeLocation("OSL", "Oslo", "Norway", "NO"),
        "OTP" to EdgeLocation("OTP", "Bucharest", "Romania", "RO"),
        "OUA" to EdgeLocation("OUA", "Ouagadougou", "Burkina Faso", "BF"),
        "PAD" to EdgeLocation("PAD", "Paderborn", "Germany", "DE"),
        "PAP" to EdgeLocation("PAP", "Port-au-Prince", "Haiti", "HT"),
        "PAT" to EdgeLocation("PAT", "Patna", "India", "IN"),
        "PBM" to EdgeLocation("PBM", "Paramaribo", "Suriname", "SR"),
        "PDX" to EdgeLocation("PDX", "Portland", "United States", "US"),
        "PEK" to EdgeLocation("PEK", "Beijing", "China", "CN"),
        "PEN" to EdgeLocation("PEN", "Penang", "Malaysia", "MY"),
        "PER" to EdgeLocation("PER", "Perth", "Australia", "AU"),
        "PHL" to EdgeLocation("PHL", "Philadelphia", "United States", "US"),
        "PHX" to EdgeLocation("PHX", "Phoenix", "United States", "US"),
        "PIT" to EdgeLocation("PIT", "Pittsburgh", "United States", "US"),
        "PKX" to EdgeLocation("PKX", "Beijing", "China", "CN"),
        "PLM" to EdgeLocation("PLM", "Palembang", "Indonesia", "ID"),
        "PNS" to EdgeLocation("PNS", "Pensacola", "United States", "US"),
        "POL" to EdgeLocation("POL", "Pemba", "Mozambique", "MZ"),
        "POS" to EdgeLocation("POS", "Port of Spain", "Trinidad and Tobago", "TT"),
        "POZ" to EdgeLocation("POZ", "Poznan", "Poland", "PL"),
        "PRG" to EdgeLocation("PRG", "Prague", "Czechia", "CZ"),
        "PRY" to EdgeLocation("PRY", "Pretoria", "South Africa", "ZA"),
        "PTY" to EdgeLocation("PTY", "Panama City", "Panama", "PA"),
        "PUJ" to EdgeLocation("PUJ", "Punta Cana", "Dominican Republic", "DO"),
        "PVG" to EdgeLocation("PVG", "Shanghai", "China", "CN"),
        "QRO" to EdgeLocation("QRO", "Queretaro", "Mexico", "MX"),
        "RAK" to EdgeLocation("RAK", "Marrakesh", "Morocco", "MA"),
        "RDU" to EdgeLocation("RDU", "Raleigh", "United States", "US"),
        "REC" to EdgeLocation("REC", "Recife", "Brazil", "BR"),
        "RFD" to EdgeLocation("RFD", "Rockford", "United States", "US"),
        "RGA" to EdgeLocation("RGA", "Rio Gallegos", "Argentina", "AR"),
        "RGL" to EdgeLocation("RGL", "Rio Grande", "Argentina", "AR"),
        "RIC" to EdgeLocation("RIC", "Richmond", "United States", "US"),
        "RIX" to EdgeLocation("RIX", "Riga", "Latvia", "LV"),
        "RMB" to EdgeLocation("RMB", "Baghdad", "Iraq", "IQ"),
        "RME" to EdgeLocation("RME", "Rome", "United States", "US"),
        "RMQ" to EdgeLocation("RMQ", "Taichung", "Taiwan", "TW"),
        "ROA" to EdgeLocation("ROA", "Roanoke", "United States", "US"),
        "ROC" to EdgeLocation("ROC", "Rochester", "United States", "US"),
        "ROV" to EdgeLocation("ROV", "Rostov-on-Don", "Russia", "RU"),
        "RSU" to EdgeLocation("RSU", "Yeosu", "South Korea", "KR"),
        "RUH" to EdgeLocation("RUH", "Riyadh", "Saudi Arabia", "SA"),
        "RUN" to EdgeLocation("RUN", "Saint-Denis", "Reunion", "RE"),
        "SAN" to EdgeLocation("SAN", "San Diego", "United States", "US"),
        "SAP" to EdgeLocation("SAP", "San Pedro Sula", "Honduras", "HN"),
        "SAT" to EdgeLocation("SAT", "San Antonio", "United States", "US"),
        "SAW" to EdgeLocation("SAW", "Istanbul", "Turkey", "TR"),
        "SCL" to EdgeLocation("SCL", "Santiago", "Chile", "CL"),
        "SCQ" to EdgeLocation("SCQ", "Santiago de Compostela", "Spain", "ES"),
        "SDF" to EdgeLocation("SDF", "Louisville", "United States", "US"),
        "SDQ" to EdgeLocation("SDQ", "Santo Domingo", "Dominican Republic", "DO"),
        "SEA" to EdgeLocation("SEA", "Seattle", "United States", "US"),
        "SFO" to EdgeLocation("SFO", "San Francisco", "United States", "US"),
        "SIN" to EdgeLocation("SIN", "Singapore", "Singapore", "SG"),
        "SJC" to EdgeLocation("SJC", "San Jose", "United States", "US"),
        "SJD" to EdgeLocation("SJD", "San Jose del Cabo", "Mexico", "MX"),
        "SJJ" to EdgeLocation("SJJ", "Sarajevo", "Bosnia and Herzegovina", "BA"),
        "SJU" to EdgeLocation("SJU", "San Juan", "Puerto Rico", "PR"),
        "SKG" to EdgeLocation("SKG", "Thessaloniki", "Greece", "GR"),
        "SKP" to EdgeLocation("SKP", "Skopje", "North Macedonia", "MK"),
        "SLC" to EdgeLocation("SLC", "Salt Lake City", "United States", "US"),
        "SMF" to EdgeLocation("SMF", "Sacramento", "United States", "US"),
        "SNU" to EdgeLocation("SNU", "Santa Clara", "Cuba", "CU"),
        "SOF" to EdgeLocation("SOF", "Sofia", "Bulgaria", "BG"),
        "SOU" to EdgeLocation("SOU", "Southampton", "United Kingdom", "GB"),
        "SSE" to EdgeLocation("SSE", "Srinagar", "India", "IN"),
        "SSG" to EdgeLocation("SSG", "Malabo", "Equatorial Guinea", "GQ"),
        "STI" to EdgeLocation("STI", "Santiago", "Dominican Republic", "DO"),
        "STL" to EdgeLocation("STL", "St. Louis", "United States", "US"),
        "STN" to EdgeLocation("STN", "London", "United Kingdom", "GB"),
        "STR" to EdgeLocation("STR", "Stuttgart", "Germany", "DE"),
        "SUV" to EdgeLocation("SUV", "Suva", "Fiji", "FJ"),
        "SVO" to EdgeLocation("SVO", "Moscow", "Russia", "RU"),
        "SVX" to EdgeLocation("SVX", "Yekaterinburg", "Russia", "RU"),
        "SXB" to EdgeLocation("SXB", "Strasbourg", "France", "FR"),
        "SXF" to EdgeLocation("SXF", "Berlin", "Germany", "DE"),
        "SYD" to EdgeLocation("SYD", "Sydney", "Australia", "AU"),
        "SYX" to EdgeLocation("SYX", "Sanya", "China", "CN"),
        "SZV" to EdgeLocation("SZV", "Suzhou", "China", "CN"),
        "SZX" to EdgeLocation("SZX", "Shenzhen", "China", "CN"),
        "TAE" to EdgeLocation("TAE", "Daegu", "South Korea", "KR"),
        "TAI" to EdgeLocation("TAI", "Taiz", "Yemen", "YE"),
        "TAK" to EdgeLocation("TAK", "Takamatsu", "Japan", "JP"),
        "TAS" to EdgeLocation("TAS", "Tashkent", "Uzbekistan", "UZ"),
        "TAY" to EdgeLocation("TAY", "Tartu", "Estonia", "EE"),
        "TBZ" to EdgeLocation("TBZ", "Tabriz", "Iran", "IR"),
        "TEN" to EdgeLocation("TEN", "Tongren", "China", "CN"),
        "TGD" to EdgeLocation("TGD", "Podgorica", "Montenegro", "ME"),
        "TGU" to EdgeLocation("TGU", "Tegucigalpa", "Honduras", "HN"),
        "THR" to EdgeLocation("THR", "Tehran", "Iran", "IR"),
        "TIA" to EdgeLocation("TIA", "Tirana", "Albania", "AL"),
        "TIF" to EdgeLocation("TIF", "Taif", "Saudi Arabia", "SA"),
        "TLL" to EdgeLocation("TLL", "Tallinn", "Estonia", "EE"),
        "TLV" to EdgeLocation("TLV", "Tel Aviv", "Israel", "IL"),
        "TNA" to EdgeLocation("TNA", "Jinan", "China", "CN"),
        "TNG" to EdgeLocation("TNG", "Tangier", "Morocco", "MA"),
        "TNR" to EdgeLocation("TNR", "Antananarivo", "Madagascar", "MG"),
        "TPE" to EdgeLocation("TPE", "Taipei", "Taiwan", "TW"),
        "TRN" to EdgeLocation("TRN", "Turin", "Italy", "IT"),
        "TSE" to EdgeLocation("TSE", "Astana", "Kazakhstan", "KZ"),
        "TSN" to EdgeLocation("TSN", "Tianjin", "China", "CN"),
        "TUN" to EdgeLocation("TUN", "Tunis", "Tunisia", "TN"),
        "TUS" to EdgeLocation("TUS", "Tucson", "United States", "US"),
        "TVC" to EdgeLocation("TVC", "Traverse City", "United States", "US"),
        "TYO" to EdgeLocation("TYO", "Tokyo", "Japan", "JP"),
        "TYS" to EdgeLocation("TYS", "Knoxville", "United States", "US"),
        "UDI" to EdgeLocation("UDI", "Uberlandia", "Brazil", "BR"),
        "UET" to EdgeLocation("UET", "Quetta", "Pakistan", "PK"),
        "UIO" to EdgeLocation("UIO", "Quito", "Ecuador", "EC"),
        "ULN" to EdgeLocation("ULN", "Ulaanbaatar", "Mongolia", "MN"),
        "URC" to EdgeLocation("URC", "Urumqi", "China", "CN"),
        "VAN" to EdgeLocation("VAN", "Van", "Turkey", "TR"),
        "VAP" to EdgeLocation("VAP", "Valparaiso", "Chile", "CL"),
        "VCP" to EdgeLocation("VCP", "Campinas", "Brazil", "BR"),
        "VIE" to EdgeLocation("VIE", "Vienna", "Austria", "AT"),
        "VNO" to EdgeLocation("VNO", "Vilnius", "Lithuania", "LT"),
        "VTE" to EdgeLocation("VTE", "Vientiane", "Laos", "LA"),
        "WAW" to EdgeLocation("WAW", "Warsaw", "Poland", "PL"),
        "WDH" to EdgeLocation("WDH", "Windhoek", "Namibia", "NA"),
        "WMI" to EdgeLocation("WMI", "Warsaw", "Poland", "PL"),
        "WUH" to EdgeLocation("WUH", "Wuhan", "China", "CN"),
        "XAP" to EdgeLocation("XAP", "Chapeco", "Brazil", "BR"),
        "XFN" to EdgeLocation("XFN", "Xiangyang", "China", "CN"),
        "XIY" to EdgeLocation("XIY", "Xi'an", "China", "CN"),
        "XMN" to EdgeLocation("XMN", "Xiamen", "China", "CN"),
        "YHZ" to EdgeLocation("YHZ", "Halifax", "Canada", "CA"),
        "YOW" to EdgeLocation("YOW", "Ottawa", "Canada", "CA"),
        "YUL" to EdgeLocation("YUL", "Montreal", "Canada", "CA"),
        "YVR" to EdgeLocation("YVR", "Vancouver", "Canada", "CA"),
        "YWG" to EdgeLocation("YWG", "Winnipeg", "Canada", "CA"),
        "YYC" to EdgeLocation("YYC", "Calgary", "Canada", "CA"),
        "YYZ" to EdgeLocation("YYZ", "Toronto", "Canada", "CA"),
        "ZAG" to EdgeLocation("ZAG", "Zagreb", "Croatia", "HR"),
        "ZDM" to EdgeLocation("ZDM", "Ramon", "Israel", "IL"),
        "ZRH" to EdgeLocation("ZRH", "Zurich", "Switzerland", "CH"),
    )

    fun fromColo(raw: String?): EdgeLocation? =
        raw?.trim()?.uppercase()?.let(locations::get)

    fun countryForColo(raw: String?): String? = fromColo(raw)?.countryCode
}
