#!/usr/bin/env python3
"""Generate WorldMapData.kt from world-atlas land-110m TopoJSON.

Output: delta-encoded rings, coordinates in decidegrees (lon*10, lat*10),
joined as `ring;ring;ring` where each ring is `x0,y0,dx,dx,dy,dx,dy,...`.
Keeps the whole land silhouette in ~40KB of Kotlin string constants.
"""
import json
import math
import sys

SRC = __import__('sys').argv[1] if len(__import__('sys').argv) > 1 else '/tmp/package/land-110m.json'
OUT = 'app/src/main/java/com/cat/client/WorldMapData.kt'

topo = json.load(open(SRC))
transform = topo['transform']
sx, sy = transform['scale']
tx, ty = transform['translate']
arcs = topo['arcs']


def decode_arc(arc):
    x = y = 0
    pts = []
    for dx, dy in arc:
        x += dx
        y += dy
        lon = tx + sx * x
        lat = ty + sy * y
        pts.append((lon, lat))
    return pts


decoded = [decode_arc(a) for a in arcs]


def ring_points(arc_indices):
    pts = []
    for idx in arc_indices:
        rev = idx < 0
        a = decoded[~idx if rev else idx]
        seq = a[::-1] if rev else a
        if pts and pts[-1] == seq[0]:
            seq = seq[1:]
        pts.extend(seq)
    # drop the closing duplicate
    if len(pts) > 1 and pts[0] == pts[-1]:
        pts = pts[:-1]
    return pts


def collect(geom, out):
    t = geom['type']
    if t == 'GeometryCollection':
        for g in geom['geometries']:
            collect(g, out)
    elif t == 'Polygon':
        for ring in geom['arcs']:
            out.append(ring_points(ring))
    elif t == 'MultiPolygon':
        for poly in geom['arcs']:
            for ring in poly:
                out.append(ring_points(ring))


rings = []
collect(topo['objects']['land'], rings)

# Decimate: skip points closer than ~0.35 deg, then round to 0.1 deg ints.
MIN_STEP2 = 0.35 ** 2
encoded = []
total_pts = 0
for ring in rings:
    kept = []
    last = None
    for lon, lat in ring:
        if last is not None:
            d2 = (lon - last[0]) ** 2 + (lat - last[1]) ** 2
            if d2 < MIN_STEP2:
                continue
        kept.append((lon, lat))
        last = (lon, lat)
    if len(kept) < 4:
        continue
    ints = []
    px = py = None
    for lon, lat in kept:
        x = int(round(lon * 10))
        y = int(round(lat * 10))
        if px is None:
            ints.extend((x, y))
        else:
            ints.extend((x - px, y - py))
        px, py = x, y
    total_pts += len(kept)
    encoded.append(','.join(str(v) for v in ints))

blob = ';'.join(encoded)

# Emit Kotlin in 90KB-safe chunks (string constants of ~8000 chars each).
CHUNK = 8000
chunks = [blob[i:i + CHUNK] for i in range(0, len(blob), CHUNK)]

kt = []
kt.append('package com.cat.client')
kt.append('')
kt.append('/**')
kt.append(' * World land silhouette for the dashboard world map (Natural Earth 110m,')
kt.append(' * public domain, via the world-atlas project). Encoded as delta-compressed')
kt.append(' * rings in decidegrees: `x0,y0,dx,dy,dx,dy,...` with rings joined by `;`.')
kt.append(' * Generated by scripts/data/gen-world-map.py — do not edit by hand.')
kt.append(' */')
kt.append('internal object WorldMapData {')
kt.append('')
kt.append('    const val POINT_COUNT = %d' % total_pts)
kt.append('')
def const_decl(name, parts):
    # Kotlin requires the operator at the END of each line.
    lines = []
    for i, c in enumerate(parts):
        suffix = ' +' if i < len(parts) - 1 else ''
        prefix = '' if i == 0 else '    '
        lines.append('%s"%s"%s' % (prefix, c, suffix))
    return '    private const val %s = ' % name + ('\n        '.join(lines))

kt.append(const_decl('D0', chunks))

kt.append('')
kt.append('    val LAND: String by lazy {')
kt.append('        ' + ' + '.join('D%d' % i for i in range(len(chunks))))
kt.append('    }')
kt.append('')
kt.append('    /** Decode rings into flat [x0,y0,dx,dy,...] arrays in decidegrees. */')
kt.append('    fun rings(): List<IntArray> = LAND.split(\';\').map { part ->')
kt.append('        val nums = part.split(\',\')')
kt.append('        IntArray(nums.size) { i -> nums[i].toInt() }')
kt.append('    }')
kt.append('}')

open(OUT, 'w', encoding='utf-8').write('\n'.join(kt) + '\n')
print('rings=%d points=%d blob=%dKB chunks=%d' % (len(encoded), total_pts, len(blob) // 1024, len(chunks)))
